// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsblKL-GdLXZ9At86VOMwbHxOaMA2aHB4',
    appId: '1:645095200875:web:03a4b285e1b4b19f1e392e',
    messagingSenderId: '645095200875',
    projectId: 'beestore-itu',
    authDomain: 'beestore-itu.firebaseapp.com',
    storageBucket: 'beestore-itu.appspot.com',
    measurementId: 'G-HRKXZ6Y07C',
    databaseURL: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMw0mB8a6RhgOpFJ1OBE9aY19lYoYGXJc',
    appId: '1:645095200875:android:8970efd0232ff2391e392e',
    messagingSenderId: '645095200875',
    projectId: 'beestore-itu',
    storageBucket: 'beestore-itu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARUL7gPpPg_CDyyAjZrqoV5oX1AMyY2iU',
    appId: '1:645095200875:ios:0f7c3d67eabf8d481e392e',
    messagingSenderId: '645095200875',
    projectId: 'beestore-itu',
    storageBucket: 'beestore-itu.appspot.com',
    iosBundleId: 'com.example.beeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARUL7gPpPg_CDyyAjZrqoV5oX1AMyY2iU',
    appId: '1:645095200875:ios:6c503e8d53544b2d1e392e',
    messagingSenderId: '645095200875',
    projectId: 'beestore-itu',
    storageBucket: 'beestore-itu.appspot.com',
    iosBundleId: 'com.example.beeStore.RunnerTests',
  );
}
